### ISSUE TITLE
Docker container does not build out of the box

### ISSUE THREAD

**Issue by yuzhu** [uwsampa/grappa-docker#1]
I am not sure that  the docker image contains sources that build out of the box. 

I got this

make[3]: **\* No rule to make target `/grappa-third-party/graph500-generator/libgraph500-generator.a', needed by`applications/demos/hello_world.exe'.  Stop.
make[2]: **\* [applications/demos/CMakeFiles/demo-hello_world.dir/all] Error 2
make[1]: **\* [applications/demos/CMakeFiles/demo-hello_world.dir/rule] Error 2
make: **\* [demo-hello_world] Error 2

when trying to build demo-hello-world. Any ideas?

**Comment by bholt** [comment]
Ah, you are quite right. Looks like the docker build broke silently a while back when we removed an option to the `configure` script, so that step in the process of building the docker image fails, which means the `/grappa-third-party` directory doesn't get created.

I'm working on rebuilding the image now (and trying to set up a way that we'll be more likely to notice if the build breaks again in the future). There also seem to be some bugs with the new docker hub website (specifically for organization repos like ours under `uwsampa`)

Thanks for reporting this!

**Comment by bholt** [comment]
I've confirmed that the new docker image works, you should be able to `docker pull uwsampa/grappa` and follow the rest of the instructions in the README.
